export enum Tag {
    CSHARP = 'c#',
    WINFORM = 'winform',
    DOTNETFRAMEWORK = '.NET Framework',
    DOTNETCORE = '.NET Core',
    DOTNETINTERNAL = '.NET Internal',
    ROSLYN = 'roslyn',
    LOWLEVEL = 'low-level',
    META = 'metaprogramming',
    REVERSING = 'reversing',
    UNITY = 'unity',
    SOCKET = 'socket',
    WINAPI = 'winapi',
    WPF = 'wpf',
    MONOGAME = 'monogame',
    GAME = 'game',
    SIMULATOR = 'simulator',
    PG = 'procedural generation',
    TEAM = 'team',
    VPL = 'vpl',
    COMPILER = 'compiler',
    PYTHON = 'python',
    C = 'c',
    RUST = 'rust',
    CREAMROLL = 'creamroll',
    BLAZOR = 'blazor',
    SERVER = 'server',
    CLIENT = 'client',
    DOCKER = 'docker',
    JAVASCRIPT = 'javascript',
    TYPESCRIPT = 'typescript',
    NODE = 'node',
    EXPRESS = 'express',
    REACT = 'react',
    MONGODB = 'mongodb',
    MEME = 'meme',
    CLI = 'cli',
    BOT = 'bot',
    GIT = 'git',
    WEB = 'web-extension',
};

export const priorities = {
    magnificent: 0,
    cool: 1,
    normal: 2,
    ambiguos: 3,
    ashamed: 4,
    humiliated: 5,
};

export const projects = [
    {
        name: 'RoyCompiler',
        link: 'https://github.com/20chan/OldProjects/tree/master/RoyCompiler',
        date: '2015-09',
        tags: [Tag.CSHARP, Tag.DOTNETFRAMEWORK],
        priority: priorities.ashamed,
        image: null,
        description: 'C# 내장 컴파일러와 텍스트 에디터를 사용한 가벼운 C# 편집/컴파일 툴',
    },
    {
        name: 'Anti-Anti-Reflection',
        link: 'https://gist.github.com/20chan/d1e95529a4d39e836ea38cc8e0d29f9d',
        date: '2017-07',
        tags: [Tag.CSHARP, Tag.DOTNETFRAMEWORK, Tag.REVERSING],
        priority: priorities.normal,
        image: null,
        description: 'PE 헤더 변조를 통한 .NET 프로그램 디컴파일 방지 프로그램',
    },
    {
        name: 'AssemblySharp',
        link: 'https://github.com/20chan/AssemblySharp',
        date: '2017-09',
        tags: [Tag.CSHARP, Tag.DOTNETCORE, Tag.DOTNETINTERNAL, Tag.LOWLEVEL],
        priority: priorities.cool,
        image: null,
        description: '어셈블리 코드를 신태틱 슈거로 C#에서 런타임에 컴파일하고 함수처럼 실행',
    },
    {
        name: 'CoreCLRCustomJIT',
        link: 'https://github.com/20chan/CoreCLRCustomJIT',
        date: '2019-04',
        tags: [Tag.CSHARP, Tag.DOTNETCORE, Tag.DOTNETINTERNAL, Tag.LOWLEVEL],
        priority: priorities.normal,
        image: null,
        description: '런타임에 JTI 컴파일러를 후킹해 IL단위 코드 몽키패치',
    },
    {
        name: 'InspectorExtender',
        link: 'https://github.com/20chan/InspectorExtender',
        date: '2019-11',
        tags: [Tag.CSHARP, Tag.UNITY, Tag.DOTNETINTERNAL],
        priority: priorities.normal,
        image: null,
        description: '유니티 인스펙터 변수/프로퍼티/메서드/ref프로퍼티 확장',
    },
    {
        name: 'hijacs',
        link: 'https://github.com/20chan/hijacs',
        date: '2020-04',
        tags: [Tag.CSHARP, Tag.DOTNETCORE, Tag.DOTNETINTERNAL],
        priority: priorities.normal,
        image: null,
        description: '런타임에 메서드 바꿔치기',
    },
    {
        name: 'RAT',
        link: null,
        date: '2015-05',
        tags: [Tag.CSHARP, Tag.WINFORM, Tag.DOTNETFRAMEWORK, Tag.WINAPI, Tag.SOCKET],
        priority: priorities.ambiguos,
        image: null,
        description: `키보드 후킹과 1:N 소켓 통신으로 구현한 키보드 로그 서버/클라이언트 프로그램`,
    },
    {
        name: 'CaptIt',
        link: 'https://github.com/20chan/CaptIt',
        youtube: 'https://youtu.be/-8k4x4MKeHM',
        date: '2015-10',
        tags: [Tag.CSHARP, Tag.WINFORM, Tag.DOTNETFRAMEWORK, Tag.WINAPI],
        priority: priorities.cool,
        image: null,
        description: `단축키와 자동 저장, 5가지 방식을 지원하는 화면 캡쳐 프로그램`,
    },
    {
        name: 'GetRGB',
        link: 'https://github.com/20chan/OldProjects/tree/master/GetRGB',
        date: '2015-12',
        tags: [Tag.CSHARP, Tag.WINFORM, Tag.DOTNETFRAMEWORK, Tag.WINAPI],
        priority: priorities.normal,
        image: null,
        description: `마우스 커서에 위치한 화면 픽셀의 색상 정보를 표시하는 프로그램`,
    },
    {
        name: 'PhillMacro',
        link: 'https://github.com/20chan/PhillMacro',
        date: '2016-01',
        tags: [Tag.CSHARP, Tag.WINFORM, Tag.DOTNETFRAMEWORK, Tag.WINAPI],
        priority: priorities.ambiguos,
        image: null,
        description: `WinForm 기반 트리거와 액션을 지정가능한 키보드/마우스 후킹 매크로 프로그램`,
    },
    {
        name: 'WindowMover',
        link: 'https://github.com/20chan/WindowMover',
        date: '2016-03',
        tags: [Tag.CSHARP, Tag.WINFORM, Tag.DOTNETFRAMEWORK, Tag.WINAPI],
        priority: priorities.ambiguos,
        image: null,
        description: `키보드 후킹을 이용한 단축키로 윈도우 창 조작`,
    },
    {
        name: 'GlobalHook',
        link: 'https://github.com/20chan/GlobalHook',
        date: '2016-06',
        tags: [Tag.CSHARP, Tag.DOTNETFRAMEWORK, Tag.WINAPI],
        priority: priorities.normal,
        image: null,
        description: `키보드/마우스 전역 후킹 라이브러리`,
    },
    {
        name: 'USBLock',
        link: 'https://github.com/20chan/USBLock',
        date: '2016-08',
        tags: [Tag.CSHARP, Tag.WINFORM, Tag.DOTNETFRAMEWORK, Tag.WINAPI],
        priority: priorities.cool,
        image: null,
        description: `USB를 키로 사용하는 화면보호기 프로그램`,
    },
    {
        name: 'Wallpaper',
        link: 'https://github.com/20chan/Wallpaper',
        date: '2016-06',
        tags: [Tag.CSHARP, Tag.WPF, Tag.DOTNETFRAMEWORK, Tag.WINAPI],
        priority: priorities.ambiguos,
        image: null,
        description: `윈도우 데스크탑 아이콘과 배경 사이에 윈도우 창을 넣는 구현체`,
    },
    {
        name: 'SolarSystemSimulator',
        link: null,
        date: '2015-06',
        tags: [Tag.CSHARP, Tag.MONOGAME, Tag.SIMULATOR],
        priority: priorities.ambiguos,
        image: null,
        description: `파티클 시스템과 물리엔진을 구현하여 만든 태양계 시뮬레이터`,
    },
    {
        name: '2048',
        link: 'https://github.com/20chan/OldProjects/tree/master/2048',
        date: '2015-10',
        tags: [Tag.CSHARP, Tag.WINFORM, Tag.DOTNETFRAMEWORK, Tag.GAME],
        priority: priorities.ambiguos,
        image: null,
        description: `2048 게임`,
    },
    {
        name: 'NeuralNetworkSimulator',
        link: 'https://github.com/20chan/NeuralNetworkSimulator',
        date: '2015-12',
        tags: [Tag.CSHARP, Tag.MONOGAME, Tag.SIMULATOR],
        priority: priorities.normal,
        image: null,
        description: `뉴런, 시냅스, 가중치 기반 뉴럴 네트워크 신호 시각화 시뮬레이터`,
    },
    {
        name: 'GCS',
        link: 'https://github.com/Big-BlueBerry/GCS',
        date: '2017-05',
        tags: [Tag.CSHARP, Tag.MONOGAME, Tag.SIMULATOR, Tag.TEAM],
        priority: priorities.magnificent,
        image: null,
        description: `인터랙티브 작도 시뮬레이션 프로그램`,
    },
    {
        name: 'Gridly',
        link: 'https://github.com/20chan/Gridly',
        youtube: 'https://youtu.be/YlKvVeV6W6A',
        date: '2018-06',
        tags: [Tag.CSHARP, Tag.MONOGAME, Tag.GAME, Tag.SIMULATOR],
        priority: priorities.normal,
        image: null,
        description: `회로 퍼즐 게임`,
    },
    {
        name: 'mapgen',
        link: 'https://youtu.be/e8-JLEsHrrg',
        youtube: 'https://youtu.be/e8-JLEsHrrg',
        date: '2019-11',
        tags: [Tag.CSHARP, Tag.UNITY, Tag.SIMULATOR, Tag.PG],
        priority: priorities.normal,
        image: null,
        description: `Procedural map generation`,
    },
    {
        name: 'Mesh 9-slicing',
        link: 'https://youtu.be/PgSg7U1UVt0',
        youtube: 'https://youtu.be/PgSg7U1UVt0',
        date: '2020-06',
        tags: [Tag.CSHARP, Tag.UNITY, Tag.PG],
        priority: priorities.normal,
        image: null,
        description: `Procedural 3d mesh 9-slicing`,
    },
    {
        name: '3D Camera',
        link: 'https://youtu.be/RTmpTyq5qwk',
        youtube: 'https://youtu.be/RTmpTyq5qwk',
        date: '2020-06',
        tags: [Tag.CSHARP, Tag.UNITY, Tag.GAME, Tag.PG],
        priority: priorities.cool,
        image: null,
        description: `Procedural 3D magic camera`,
    },
    {
        name: 'spider',
        link: 'https://youtu.be/KcTFCb4MYHg',
        youtube: 'https://youtu.be/KcTFCb4MYHg',
        date: '2020-06',
        tags: [Tag.CSHARP, Tag.UNITY, Tag.SIMULATOR, Tag.PG],
        priority: priorities.normal,
        image: null,
        description: `Procedural leg IK based movements`,
    },
    {
        name: 'UnitySniper',
        link: 'https://gist.github.com/20chan/1199b5100c96fc146d6aff8f454bba5a',
        date: '2020-03',
        tags: [Tag.CSHARP, Tag.UNITY, Tag.DOTNETCORE, Tag.META, Tag.DOTNETINTERNAL],
        priority: priorities.normal,
        image: null,
        description: `유니티 에디터 런타임에 동적 C# 스크립트 실행 도구`,
    },
    {
        name: 'Blocky',
        link: 'https://github.com/20chan/Blocky',
        date: '2016-06',
        tags: [Tag.CSHARP, Tag.WINFORM, Tag.DOTNETFRAMEWORK, Tag.META, Tag.VPL],
        priority: priorities.ambiguos,
        image: null,
        description: `최소한의 인터페이스로 작동하는 VPL`,
    },
    {
        name: 'Linking',
        link: 'https://github.com/20chan/Linking-VPL',
        date: '2016-12',
        tags: [Tag.CSHARP, Tag.WINFORM, Tag.DOTNETFRAMEWORK, Tag.META, Tag.VPL],
        priority: priorities.normal,
        image: null,
        description: `완성도 있는 VPL`,
    },
    {
        name: 'bumble',
        link: 'https://github.com/20chan/bumble',
        date: '2017-03',
        tags: [Tag.PYTHON, Tag.COMPILER],
        priority: priorities.ambiguos,
        image: null,
        description: `가벼운 언어 스펙과 인터프리터`,
    },
    {
        name: 'claculator',
        link: 'https://github.com/20chan/claculator',
        date: '2017-08',
        tags: [Tag.PYTHON, Tag.C, Tag.COMPILER],
        priority: priorities.normal,
        image: null,
        description: `계산기 컴파일러의 python 구현체와 바이트코드 실행 VM의 c 구현체`,
    },
    {
        name: 'shrew',
        link: 'https://github.com/20chan/shrew',
        date: '2018-08',
        tags: [Tag.CSHARP, Tag.COMPILER],
        priority: priorities.normal,
        image: null,
        description: `패턴 기반 인터프리터 언어와 구현체`,
    },
    {
        name: 'SimpleWebServer',
        link: 'https://github.com/20chan/SimpleWebServer',
        date: '2018-09',
        tags: [Tag.CSHARP, Tag.SERVER],
        priority: priorities.normal,
        image: null,
        description: `HttpListener 기반 어트리뷰트-리플렉션 인터페이스를 사용한 웹서버 라이브러리`,
    },
    {
        name: 'CreamRoll',
        link: 'https://github.com/20chan/CreamRoll',
        date: '2019-06',
        tags: [Tag.CSHARP, Tag.SERVER, Tag.CREAMROLL],
        priority: priorities.cool,
        image: null,
        description: `DSL을 지원하는 바닥부터 구현된 서버 라이브러리`,
    },
    {
        name: 'custard',
        link: 'https://github.com/20chan/custard',
        date: '2019-06',
        tags: [Tag.CSHARP, Tag.SERVER, Tag.CREAMROLL],
        priority: priorities.ambiguos,
        image: null,
        description: `데이터 버젼관리 서버`,
    },
    {
        name: 'cigar',
        link: 'https://github.com/20chan/cigar',
        date: '2019-12',
        tags: [Tag.CSHARP, Tag.SERVER, Tag.CLIENT, Tag.CREAMROLL],
        priority: priorities.ambiguos,
        image: null,
        description: `롤링페이퍼 서비스`,
    },
    {
        name: 'lp',
        link: 'https://github.com/20chan/lp',
        date: '2020-01',
        tags: [Tag.CSHARP, Tag.SERVER, Tag.CLIENT, Tag.CREAMROLL],
        priority: priorities.normal,
        image: null,
        description: `블로그 서비스`,
    },
    {
        name: 'kahan',
        link: 'https://github.com/20chan/kahan',
        date: '2020-05',
        tags: [Tag.CSHARP, Tag.SERVER, Tag.CLIENT, Tag.BLAZOR],
        priority: priorities.normal,
        image: null,
        description: `Balzor SignalR을 사용한 원격 음악 플레이어 조작 대시보드`,
    },
    {
        name: 'aka',
        link: 'https://github.com/20chan/aka-archive',
        date: '2020-05',
        tags: [Tag.CSHARP, Tag.SERVER, Tag.CLIENT, Tag.BLAZOR],
        priority: priorities.normal,
        image: null,
        description: `Url shortener`,
    },
    {
        name: 'note',
        link: 'https://github.com/20chan/note',
        date: '2020-06',
        tags: [Tag.TYPESCRIPT, Tag.NODE, Tag.EXPRESS, Tag.REACT, Tag.SERVER, Tag.CLIENT, Tag.DOCKER],
        priority: priorities.normal,
        image: null,
        description: `패턴 기반 인터프리터 언어와 구현체`,
    },
    {
        name: 'Fast A+B',
        link: 'https://gist.github.com/20chan/67fff1d3da8549d8540239c39f3f8bcd',
        date: '2019-06',
        tags: [Tag.CSHARP],
        priority: priorities.normal,
        image: null,
        description: `콘솔 io 버퍼링 관련 분석 및 해결책`,
    },
    {
        name: 'cirno',
        link: 'https://github.com/20chan/cirno',
        date: '2019-10',
        tags: [Tag.CSHARP],
        priority: priorities.normal,
        image: null,
        description: `기하 라이브러리`,
    },
    {
        name: 'commit-twitter-bot',
        link: 'https://github.com/20chan/commit-twitter-bot',
        date: '2017-01',
        tags: [Tag.PYTHON, Tag.BOT],
        priority: priorities.ashamed,
        image: null,
        description: `1일커밋을 지키지 않으면 트위터로 알림을 보내주는 봇`,
    },
    {
        name: 'aheuithon',
        link: 'https://github.com/20chan/aheuithon',
        date: '2019-10',
        tags: [Tag.PYTHON, Tag.MEME],
        priority: priorities.cool,
        image: null,
        description: `파이썬 아희 커스텀 코덱`,
    },
    {
        name: 'calc-repl-rs',
        link: 'https://github.com/20chan/calc-repl-rs',
        date: '2018-10',
        tags: [Tag.RUST, Tag.CLI],
        priority: priorities.ambiguos,
        image: null,
        description: `계산기 REPL`,
    },
    {
        name: 'tic-tac-toe-rs',
        link: 'https://github.com/20chan/tic-tac-toe-rs',
        date: '2018-10',
        tags: [Tag.RUST, Tag.CLI],
        priority: priorities.ambiguos,
        image: null,
        description: `틱택토`,
    },
    {
        name: 'Update',
        link: 'https://github.com/20chan/OldProjects/tree/master/Update',
        date: '2015-05',
        tags: [Tag.CSHARP, Tag.DOTNETFRAMEWORK, Tag.WINFORM],
        priority: priorities.ambiguos,
        image: null,
        description: `드롭박스 OAuth API를 사용한 프로젝트들의 버전 관리 자동화 프로그램`,
    },
    {
        name: 'AssistantManager',
        link: 'https://github.com/20chan/OldProjects/tree/master/Assistant%20Manager',
        date: '2015-08',
        tags: [Tag.CSHARP, Tag.DOTNETFRAMEWORK, Tag.WINFORM],
        priority: priorities.ambiguos,
        image: null,
        description: `MS Speech API를 사용해 음성 인식으로 명령을 실행하는 프로그램`,
    },
    {
        name: 'CodeCount',
        link: 'https://github.com/20chan/CodeCounter',
        date: '2016-05',
        tags: [Tag.CSHARP, Tag.DOTNETFRAMEWORK, Tag.WINFORM],
        priority: priorities.normal,
        image: null,
        description: `프로젝트의 파일을 규칙으로 필터링해 전체 코드 라인 계산`,
    },
    {
        name: 'Excelly',
        link: 'https://github.com/20chan/Excelly',
        date: '2016-09',
        tags: [Tag.CSHARP, Tag.DOTNETFRAMEWORK, Tag.WINFORM],
        priority: priorities.normal,
        image: null,
        description: `외부 리스트, 함수 등 연산을 지원하는 스프레드시트 통계 프로그램`,
    },
    {
        name: 'AdSlide',
        link: 'https://github.com/20chan/UIEngine',
        date: '2016-10',
        tags: [Tag.CSHARP, Tag.DOTNETFRAMEWORK, Tag.WINFORM],
        priority: priorities.normal,
        image: null,
        description: `씬 전환, 애니메이션 등을 지원하는 슬라이드 쇼 프로그램`,
    },
    {
        name: 'ChristmasTree',
        link: 'https://github.com/20chan/ChristmasTree',
        date: '2016-12',
        tags: [Tag.PYTHON, Tag.CLI],
        priority: priorities.normal,
        image: null,
        description: `터미널에서 눈내리는 크리스마스 트리`,
    },
    {
        name: 'img2term',
        link: 'https://github.com/20chan/img2term',
        date: '2017-06',
        tags: [Tag.PYTHON, Tag.CLI],
        priority: priorities.normal,
        image: null,
        description: `이미지를 ansi code로 변환하여 터미널에서 출력`,
    },
    {
        name: 'pre-commit',
        link: 'https://gist.github.com/20chan/4e91dabcd319df14bff40ca2a42caa19',
        date: '2020-08',
        tags: [Tag.GIT],
        priority: priorities.normal,
        image: null,
        description: `git 유니티에서 빈 폴더의 meta파일을 unstage시키는 pre-commit 훅`,
    },
    {
        name: 'clickup-assign-me',
        link: 'https://github.com/20chan/clickup-assign-me',
        date: '2020-01',
        tags: [Tag.JAVASCRIPT, Tag.WEB],
        priority: priorities.normal,
        image: null,
        description: `클릭업에 assign me 버튼을 추가해주는 웹 확장 프로그램`,
    },
    {
        name: 'github-now',
        link: 'https://github.com/20chan/github-now',
        date: '2020-07',
        tags: [Tag.TYPESCRIPT, Tag.WEB],
        priority: priorities.ambiguos,
        image: null,
        description: `현재 듣고 있는 노래를 깃헙 프로필에 실시간으로 띄워주는 웹 확장 프로그램`,
    },
];